# Generated by Django 6.0.7 on 2026-07-18 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos_puntuacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillareto',
            name='enunciado_pregunta',
            field=models.TextField(blank=True, help_text='Pregunta molde que se copiará automáticamente a cada reto generado.'),
        ),
        migrations.CreateModel(
            name='PlantillaOpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opcion', models.CharField(max_length=255)),
                ('es_correcta', models.BooleanField(default=False)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_molde', to='retos_puntuacion.plantillareto')),
            ],
        ),
    ]
