# Generated by Django 6.0.7 on 2026-07-18 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('honeypot', '0001_initial'),
        ('retos_puntuacion', '0002_plantillareto_enunciado_pregunta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reto',
            name='ataque_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retos_generados', to='honeypot.ataquehoneypot'),
        ),
        migrations.AlterUniqueTogether(
            name='reto',
            unique_together={('ataque_origen', 'curso')},
        ),
    ]
