# Generated by Django 4.2.30 on 2026-09-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos_puntuacion', '0004_alter_insignia_id_alter_intentoreto_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillareto',
            name='credenciales_practica',
            field=models.CharField(blank=True, help_text='Usuario/contraseña de práctica a usar en este reto, ej: usuario=admin, contraseña=123456', max_length=255),
        ),
        migrations.AddField(
            model_name='plantillareto',
            name='instrucciones_practica',
            field=models.TextField(blank=True, help_text='Pasos y comandos exactos que el estudiante debe ejecutar contra el Cowrie real'),
        ),
        migrations.AddField(
            model_name='plantillareto',
            name='orden',
            field=models.PositiveIntegerField(default=1, help_text='Orden en que aparece el reto dentro de su nivel (1, 2, 3...)'),
        ),
    ]
