# Generated by Django 6.0.7 on 2026-07-21 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(default='📘', max_length=10)),
                ('orden', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('contenido', models.TextField()),
                ('orden', models.PositiveIntegerField(default=1)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='lecciones.modulo')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='LeccionCompletada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_completada', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(limit_choices_to={'rol': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='lecciones_completadas', to=settings.AUTH_USER_MODEL)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completadas_por', to='lecciones.leccion')),
            ],
            options={
                'unique_together': {('estudiante', 'leccion')},
            },
        ),
    ]
