# Generated by Django 6.0.7 on 2026-07-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['nivel', 'orden']},
        ),
        migrations.AddField(
            model_name='modulo',
            name='nivel',
            field=models.CharField(choices=[('basico', 'Básico'), ('avanzado', 'Avanzado')], default='basico', max_length=10),
        ),
    ]
