# Generated by Django 4.2.30 on 2026-10-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0003_alter_leccion_id_alter_leccioncompletada_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='dato_curioso',
            field=models.TextField(blank=True, help_text='Dato curioso "¿Sabías qué...?" que se muestra en una tarjeta destacada.'),
        ),
    ]
