# Generated by Django 4.2.30 on 2026-10-07 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecciones', '0004_leccion_dato_curioso'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaEstudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('icono', models.CharField(default='🃏', max_length=10)),
                ('titulo', models.CharField(max_length=100)),
                ('analogia', models.CharField(max_length=255)),
                ('peligro', models.PositiveSmallIntegerField(default=1, help_text='1 = bajo, 2 = medio, 3 = alto')),
                ('que_es', models.TextField()),
                ('como_se_ve', models.TextField()),
                ('como_defenderse', models.TextField()),
                ('solo_teoria', models.BooleanField(default=False)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='lecciones.modulo')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('modulo', 'orden')},
            },
        ),
    ]
