--
-- PostgreSQL database dump
--

\restrict VHfBqszWjkkvfnvREOWVwWFxovAQs72tDbXJii2xqKUQHCeMaZX24Gstxhk0wif

-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: cyberedu_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO cyberedu_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: cyberedu_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: cyberedu_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO cyberedu_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: cyberedu_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: cyberedu_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO cyberedu_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: cyberedu_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cursos_curso; Type: TABLE; Schema: public; Owner: cyberedu_user
--

CREATE TABLE public.cursos_curso (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion text NOT NULL,
    cupo_maximo integer NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    activo boolean NOT NULL,
    profesor_id bigint NOT NULL,
    CONSTRAINT cursos_curso_cupo_maximo_check CHECK ((cupo_maximo >= 0))
);


ALTER TABLE public.cursos_curso OWNER TO cyberedu_user;

--
-- Name: cursos_curso_id_seq; Type: SEQUENCE; Schema: public; Owner: cyberedu_user
--

ALTER TABLE public.cursos_curso ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cursos_curso_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cursos_inscripcion; Type: TABLE; Schema: public; Owner: cyberedu_user
--

CREATE TABLE public.cursos_inscripcion (
    id bigint NOT NULL,
    fecha_inscripcion timestamp with time zone NOT NULL,
    curso_id bigint NOT NULL,
    estudiante_id bigint NOT NULL
);


ALTER TABLE public.cursos_inscripcion OWNER TO cyberedu_user;

--
-- Name: cursos_inscripcion_id_seq; Type: SEQUENCE; Schema: public; Owner: cyberedu_user
--

ALTER TABLE public.cursos_inscripcion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cursos_inscripcion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: cyberedu_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO cyberedu_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: cyberedu_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: cyberedu_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO cyberedu_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: cyberedu_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: cyberedu_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO cyberedu_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: cyberedu_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: cyberedu_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO cyberedu_user;

--
-- Name: honeypot_ataquehoneypot; Type: TABLE; Schema: public; Owner: cyberedu_user
--

CREATE TABLE public.honeypot_ataquehoneypot (
    id bigint NOT NULL,
    ip_origen inet NOT NULL,
    usuario_probado character varying(100) NOT NULL,
    contrasena_probada character varying(100) NOT NULL,
    protocolo character varying(20) NOT NULL,
    sesion_cowrie character varying(64) NOT NULL,
    eventid_original character varying(100) NOT NULL,
    timestamp_evento timestamp with time zone NOT NULL,
    fecha_ingesta timestamp with time zone NOT NULL,
    procesado boolean NOT NULL,
    tipo_ataque_id bigint
);


ALTER TABLE public.honeypot_ataquehoneypot OWNER TO cyberedu_user;

--
-- Name: honeypot_ataquehoneypot_id_seq; Type: SEQUENCE; Schema: public; Owner: cyberedu_user
--

ALTER TABLE public.honeypot_ataquehoneypot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.honeypot_ataquehoneypot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: retos_puntuacion_insignia; Type: TABLE; Schema: public; Owner: cyberedu_user
--

CREATE TABLE public.retos_puntuacion_insignia (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion text NOT NULL,
    condicion_logro character varying(255) NOT NULL,
    icono character varying(255) NOT NULL
);


ALTER TABLE public.retos_puntuacion_insignia OWNER TO cyberedu_user;

--
-- Name: retos_puntuacion_insignia_id_seq; Type: SEQUENCE; Schema: public; Owner: cyberedu_user
--

ALTER TABLE public.retos_puntuacion_insignia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.retos_puntuacion_insignia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: retos_puntuacion_intentoreto; Type: TABLE; Schema: public; Owner: cyberedu_user
--

CREATE TABLE public.retos_puntuacion_intentoreto (
    id bigint NOT NULL,
    es_correcto boolean NOT NULL,
    xp_otorgado integer NOT NULL,
    fecha_intento timestamp with time zone NOT NULL,
    estudiante_id bigint NOT NULL,
    respuesta_seleccionada_id bigint NOT NULL,
    reto_id bigint NOT NULL,
    CONSTRAINT retos_puntuacion_intentoreto_xp_otorgado_check CHECK ((xp_otorgado >= 0))
);


ALTER TABLE public.retos_puntuacion_intentoreto OWNER TO cyberedu_user;

--
-- Name: retos_puntuacion_intentoreto_id_seq; Type: SEQUENCE; Schema: public; Owner: cyberedu_user
--

ALTER TABLE public.retos_puntuacion_intentoreto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.retos_puntuacion_intentoreto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: retos_puntuacion_nivel; Type: TABLE; Schema: public; Owner: cyberedu_user
--

CREATE TABLE public.retos_puntuacion_nivel (
    id bigint NOT NULL,
    numero_nivel integer NOT NULL,
    nombre_nivel character varying(50) NOT NULL,
    xp_minimo integer NOT NULL,
    xp_maximo integer,
    CONSTRAINT retos_puntuacion_nivel_numero_nivel_check CHECK ((numero_nivel >= 0)),
    CONSTRAINT retos_puntuacion_nivel_xp_maximo_check CHECK ((xp_maximo >= 0)),
    CONSTRAINT retos_puntuacion_nivel_xp_minimo_check CHECK ((xp_minimo >= 0))
);


ALTER TABLE public.retos_puntuacion_nivel OWNER TO cyberedu_user;

--
-- Name: retos_puntuacion_nivel_id_seq; Type: SEQUENCE; Schema: public; Owner: cyberedu_user
--

ALTER TABLE public.retos_puntuacion_nivel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.retos_puntuacion_nivel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: retos_puntuacion_opcionrespuesta; Type: TABLE; Schema: public; Owner: cyberedu_user
--

CREATE TABLE public.retos_puntuacion_opcionrespuesta (
    id bigint NOT NULL,
    texto_opcion character varying(255) NOT NULL,
    es_correcta boolean NOT NULL,
    pregunta_id bigint NOT NULL
);


ALTER TABLE public.retos_puntuacion_opcionrespuesta OWNER TO cyberedu_user;

--
-- Name: retos_puntuacion_opcionrespuesta_id_seq; Type: SEQUENCE; Schema: public; Owner: cyberedu_user
--

ALTER TABLE public.retos_puntuacion_opcionrespuesta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.retos_puntuacion_opcionrespuesta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: retos_puntuacion_perfilestudiante; Type: TABLE; Schema: public; Owner: cyberedu_user
--

CREATE TABLE public.retos_puntuacion_perfilestudiante (
    id bigint NOT NULL,
    xp_total integer NOT NULL,
    nivel_id bigint,
    usuario_id bigint NOT NULL,
    CONSTRAINT retos_puntuacion_perfilestudiante_xp_total_check CHECK ((xp_total >= 0))
);


ALTER TABLE public.retos_puntuacion_perfilestudiante OWNER TO cyberedu_user;

--
-- Name: retos_puntuacion_perfilestudiante_id_seq; Type: SEQUENCE; Schema: public; Owner: cyberedu_user
--

ALTER TABLE public.retos_puntuacion_perfilestudiante ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.retos_puntuacion_perfilestudiante_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: retos_puntuacion_plantillaopcionrespuesta; Type: TABLE; Schema: public; Owner: cyberedu_user
--

CREATE TABLE public.retos_puntuacion_plantillaopcionrespuesta (
    id bigint NOT NULL,
    texto_opcion character varying(255) NOT NULL,
    es_correcta boolean NOT NULL,
    plantilla_id bigint NOT NULL
);


ALTER TABLE public.retos_puntuacion_plantillaopcionrespuesta OWNER TO cyberedu_user;

--
-- Name: retos_puntuacion_plantillaopcionrespuesta_id_seq; Type: SEQUENCE; Schema: public; Owner: cyberedu_user
--

ALTER TABLE public.retos_puntuacion_plantillaopcionrespuesta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.retos_puntuacion_plantillaopcionrespuesta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: retos_puntuacion_plantillareto; Type: TABLE; Schema: public; Owner: cyberedu_user
--

CREATE TABLE public.retos_puntuacion_plantillareto (
    id bigint NOT NULL,
    titulo character varying(150) NOT NULL,
    descripcion text NOT NULL,
    xp_recompensa integer NOT NULL,
    tipo_ataque_id bigint NOT NULL,
    enunciado_pregunta text NOT NULL,
    CONSTRAINT retos_puntuacion_plantillareto_xp_recompensa_check CHECK ((xp_recompensa >= 0))
);


ALTER TABLE public.retos_puntuacion_plantillareto OWNER TO cyberedu_user;

--
-- Name: retos_puntuacion_plantillareto_id_seq; Type: SEQUENCE; Schema: public; Owner: cyberedu_user
--

ALTER TABLE public.retos_puntuacion_plantillareto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.retos_puntuacion_plantillareto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: retos_puntuacion_preguntaquiz; Type: TABLE; Schema: public; Owner: cyberedu_user
--

CREATE TABLE public.retos_puntuacion_preguntaquiz (
    id bigint NOT NULL,
    enunciado text NOT NULL,
    orden integer NOT NULL,
    reto_id bigint NOT NULL,
    CONSTRAINT retos_puntuacion_preguntaquiz_orden_check CHECK ((orden >= 0))
);


ALTER TABLE public.retos_puntuacion_preguntaquiz OWNER TO cyberedu_user;

--
-- Name: retos_puntuacion_preguntaquiz_id_seq; Type: SEQUENCE; Schema: public; Owner: cyberedu_user
--

ALTER TABLE public.retos_puntuacion_preguntaquiz ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.retos_puntuacion_preguntaquiz_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: retos_puntuacion_reto; Type: TABLE; Schema: public; Owner: cyberedu_user
--

CREATE TABLE public.retos_puntuacion_reto (
    id bigint NOT NULL,
    fecha_generacion timestamp with time zone NOT NULL,
    activo boolean NOT NULL,
    curso_id bigint NOT NULL,
    plantilla_id bigint NOT NULL,
    ataque_origen_id bigint
);


ALTER TABLE public.retos_puntuacion_reto OWNER TO cyberedu_user;

--
-- Name: retos_puntuacion_reto_id_seq; Type: SEQUENCE; Schema: public; Owner: cyberedu_user
--

ALTER TABLE public.retos_puntuacion_reto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.retos_puntuacion_reto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: retos_puntuacion_tipoataque; Type: TABLE; Schema: public; Owner: cyberedu_user
--

CREATE TABLE public.retos_puntuacion_tipoataque (
    id bigint NOT NULL,
    nombre character varying(80) NOT NULL,
    descripcion text NOT NULL
);


ALTER TABLE public.retos_puntuacion_tipoataque OWNER TO cyberedu_user;

--
-- Name: retos_puntuacion_tipoataque_id_seq; Type: SEQUENCE; Schema: public; Owner: cyberedu_user
--

ALTER TABLE public.retos_puntuacion_tipoataque ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.retos_puntuacion_tipoataque_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: retos_puntuacion_usuarioinsignia; Type: TABLE; Schema: public; Owner: cyberedu_user
--

CREATE TABLE public.retos_puntuacion_usuarioinsignia (
    id bigint NOT NULL,
    fecha_obtencion timestamp with time zone NOT NULL,
    insignia_id bigint NOT NULL,
    usuario_id bigint NOT NULL
);


ALTER TABLE public.retos_puntuacion_usuarioinsignia OWNER TO cyberedu_user;

--
-- Name: retos_puntuacion_usuarioinsignia_id_seq; Type: SEQUENCE; Schema: public; Owner: cyberedu_user
--

ALTER TABLE public.retos_puntuacion_usuarioinsignia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.retos_puntuacion_usuarioinsignia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios_usuario; Type: TABLE; Schema: public; Owner: cyberedu_user
--

CREATE TABLE public.usuarios_usuario (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    rol character varying(20) NOT NULL,
    telegram_chat_id character varying(50),
    telegram_vinculado boolean NOT NULL,
    codigo_vinculacion_expira timestamp with time zone,
    codigo_vinculacion_telegram character varying(10)
);


ALTER TABLE public.usuarios_usuario OWNER TO cyberedu_user;

--
-- Name: usuarios_usuario_groups; Type: TABLE; Schema: public; Owner: cyberedu_user
--

CREATE TABLE public.usuarios_usuario_groups (
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.usuarios_usuario_groups OWNER TO cyberedu_user;

--
-- Name: usuarios_usuario_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: cyberedu_user
--

ALTER TABLE public.usuarios_usuario_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_usuario_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios_usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: cyberedu_user
--

ALTER TABLE public.usuarios_usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios_usuario_user_permissions; Type: TABLE; Schema: public; Owner: cyberedu_user
--

CREATE TABLE public.usuarios_usuario_user_permissions (
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.usuarios_usuario_user_permissions OWNER TO cyberedu_user;

--
-- Name: usuarios_usuario_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: cyberedu_user
--

ALTER TABLE public.usuarios_usuario_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_usuario_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: cyberedu_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: cyberedu_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: cyberedu_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_usuario
22	Can change user	6	change_usuario
23	Can delete user	6	delete_usuario
24	Can view user	6	view_usuario
25	Can add inscripcion	8	add_inscripcion
26	Can change inscripcion	8	change_inscripcion
27	Can delete inscripcion	8	delete_inscripcion
28	Can view inscripcion	8	view_inscripcion
29	Can add curso	7	add_curso
30	Can change curso	7	change_curso
31	Can delete curso	7	delete_curso
32	Can view curso	7	view_curso
33	Can add plantilla reto	14	add_plantillareto
34	Can change plantilla reto	14	change_plantillareto
35	Can delete plantilla reto	14	delete_plantillareto
36	Can view plantilla reto	14	view_plantillareto
37	Can add reto	16	add_reto
38	Can change reto	16	change_reto
39	Can delete reto	16	delete_reto
40	Can view reto	16	view_reto
41	Can add usuario insignia	18	add_usuarioinsignia
42	Can change usuario insignia	18	change_usuarioinsignia
43	Can delete usuario insignia	18	delete_usuarioinsignia
44	Can view usuario insignia	18	view_usuarioinsignia
45	Can add perfil estudiante	13	add_perfilestudiante
46	Can change perfil estudiante	13	change_perfilestudiante
47	Can delete perfil estudiante	13	delete_perfilestudiante
48	Can view perfil estudiante	13	view_perfilestudiante
49	Can add intento reto	10	add_intentoreto
50	Can change intento reto	10	change_intentoreto
51	Can delete intento reto	10	delete_intentoreto
52	Can view intento reto	10	view_intentoreto
53	Can add nivel	11	add_nivel
54	Can change nivel	11	change_nivel
55	Can delete nivel	11	delete_nivel
56	Can view nivel	11	view_nivel
57	Can add tipo ataque	17	add_tipoataque
58	Can change tipo ataque	17	change_tipoataque
59	Can delete tipo ataque	17	delete_tipoataque
60	Can view tipo ataque	17	view_tipoataque
61	Can add insignia	9	add_insignia
62	Can change insignia	9	change_insignia
63	Can delete insignia	9	delete_insignia
64	Can view insignia	9	view_insignia
65	Can add pregunta quiz	15	add_preguntaquiz
66	Can change pregunta quiz	15	change_preguntaquiz
67	Can delete pregunta quiz	15	delete_preguntaquiz
68	Can view pregunta quiz	15	view_preguntaquiz
69	Can add opcion respuesta	12	add_opcionrespuesta
70	Can change opcion respuesta	12	change_opcionrespuesta
71	Can delete opcion respuesta	12	delete_opcionrespuesta
72	Can view opcion respuesta	12	view_opcionrespuesta
73	Can add ataque honeypot	19	add_ataquehoneypot
74	Can change ataque honeypot	19	change_ataquehoneypot
75	Can delete ataque honeypot	19	delete_ataquehoneypot
76	Can view ataque honeypot	19	view_ataquehoneypot
77	Can add plantilla opcion respuesta	20	add_plantillaopcionrespuesta
78	Can change plantilla opcion respuesta	20	change_plantillaopcionrespuesta
79	Can delete plantilla opcion respuesta	20	delete_plantillaopcionrespuesta
80	Can view plantilla opcion respuesta	20	view_plantillaopcionrespuesta
\.


--
-- Data for Name: cursos_curso; Type: TABLE DATA; Schema: public; Owner: cyberedu_user
--

COPY public.cursos_curso (id, nombre, descripcion, cupo_maximo, fecha_creacion, activo, profesor_id) FROM stdin;
1	Ciberseguridad 11-A		30	2026-07-16 19:59:53.822147-05	t	5
\.


--
-- Data for Name: cursos_inscripcion; Type: TABLE DATA; Schema: public; Owner: cyberedu_user
--

COPY public.cursos_inscripcion (id, fecha_inscripcion, curso_id, estudiante_id) FROM stdin;
1	2026-07-16 21:23:03.36391-05	1	3
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: cyberedu_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-07-10 10:40:02.059795-05	4	karol (estudiante)	1	[{"added": {}}]	6	1
2	2026-07-16 19:59:53.823151-05	1	Ciberseguridad 11-A	1	[{"added": {}}]	7	1
3	2026-07-16 21:38:32.579981-05	1	Nivel 1 — Aprendiz	1	[{"added": {}}]	11	1
4	2026-07-16 21:39:33.209995-05	2	Nivel 2 — Explorador	1	[{"added": {}}]	11	1
5	2026-07-16 21:40:27.375329-05	3	Nivel 3 — Guardian	1	[{"added": {}}]	11	1
6	2026-07-17 06:15:31.33245-05	1	Fuerza bruta SSH	1	[{"added": {}}]	17	1
7	2026-07-17 06:16:31.277877-05	1	Identifica el ataque SSH	1	[{"added": {}}]	14	1
8	2026-07-17 06:16:57.867624-05	1	Identifica el ataque SSH (Ciberseguridad 11-A)	1	[{"added": {}}]	16	1
9	2026-07-17 06:19:10.759945-05	1	¿Qué tipo de ataque representa este evento?	1	[{"added": {}}, {"added": {"name": "opcion respuesta", "object": "Fuerza bruta SSH"}}, {"added": {"name": "opcion respuesta", "object": "Ataque de phishing"}}, {"added": {"name": "opcion respuesta", "object": "Inyecci\\u00f3n SQL"}}, {"added": {"name": "opcion respuesta", "object": "Ataque DDoS"}}]	15	1
10	2026-07-17 06:29:10.228143-05	1	Primer paso	1	[{"added": {}}]	9	1
11	2026-07-18 14:50:29.263897-05	1	Identifica el ataque SSH	2	[{"changed": {"fields": ["Enunciado pregunta"]}}, {"added": {"name": "plantilla opcion respuesta", "object": "Fuerza bruta SSH"}}, {"added": {"name": "plantilla opcion respuesta", "object": "Ataque de phishing"}}, {"added": {"name": "plantilla opcion respuesta", "object": "Inyecci\\u00f3n SQL"}}, {"added": {"name": "plantilla opcion respuesta", "object": "Ataque DDoS"}}]	14	1
12	2026-07-18 16:13:38.668144-05	2	Ciberseguridad 11-B	3		7	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: cyberedu_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
6	usuarios	usuario
7	cursos	curso
8	cursos	inscripcion
9	retos_puntuacion	insignia
10	retos_puntuacion	intentoreto
11	retos_puntuacion	nivel
12	retos_puntuacion	opcionrespuesta
13	retos_puntuacion	perfilestudiante
14	retos_puntuacion	plantillareto
15	retos_puntuacion	preguntaquiz
16	retos_puntuacion	reto
17	retos_puntuacion	tipoataque
18	retos_puntuacion	usuarioinsignia
19	honeypot	ataquehoneypot
20	retos_puntuacion	plantillaopcionrespuesta
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: cyberedu_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-07-09 22:29:26.177888-05
2	contenttypes	0002_remove_content_type_name	2026-07-09 22:29:26.182977-05
3	auth	0001_initial	2026-07-09 22:29:26.250883-05
4	auth	0002_alter_permission_name_max_length	2026-07-09 22:29:26.260037-05
5	auth	0003_alter_user_email_max_length	2026-07-09 22:29:26.266029-05
6	auth	0004_alter_user_username_opts	2026-07-09 22:29:26.278611-05
7	auth	0005_alter_user_last_login_null	2026-07-09 22:29:26.287436-05
8	auth	0006_require_contenttypes_0002	2026-07-09 22:29:26.293762-05
9	auth	0007_alter_validators_add_error_messages	2026-07-09 22:29:26.303442-05
10	auth	0008_alter_user_username_max_length	2026-07-09 22:29:26.315299-05
11	auth	0009_alter_user_last_name_max_length	2026-07-09 22:29:26.328781-05
12	auth	0010_alter_group_name_max_length	2026-07-09 22:29:26.34269-05
13	auth	0011_update_proxy_permissions	2026-07-09 22:29:26.3581-05
14	auth	0012_alter_user_first_name_max_length	2026-07-09 22:29:26.362918-05
15	usuarios	0001_initial	2026-07-09 22:29:26.442456-05
16	admin	0001_initial	2026-07-09 22:29:26.486569-05
17	admin	0002_logentry_remove_auto_add	2026-07-09 22:29:26.509066-05
18	admin	0003_logentry_add_action_flag_choices	2026-07-09 22:29:26.520885-05
19	sessions	0001_initial	2026-07-09 22:29:26.550417-05
20	cursos	0001_initial	2026-07-16 19:51:35.443989-05
21	retos_puntuacion	0001_initial	2026-07-16 21:31:54.907411-05
22	honeypot	0001_initial	2026-07-18 10:38:36.232399-05
23	retos_puntuacion	0002_plantillareto_enunciado_pregunta_and_more	2026-07-18 14:35:50.392661-05
24	retos_puntuacion	0003_reto_ataque_origen_alter_reto_unique_together	2026-07-18 16:03:10.444862-05
25	usuarios	0002_usuario_codigo_vinculacion_expira_and_more	2026-07-18 16:32:15.944564-05
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: cyberedu_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
lkfuv2z2mahzgowq2beiyp5ymblxi6pl	.eJxVjDsOwjAQBe_iGlnxZ-0NJX3OENlrLw4gR4qTCnF3EikFtDPz3luMYVvLuLW8jFMSV6HE5ZfFQM9cD5Eeod5nSXNdlynKI5GnbXKYU37dzvbvoIRW9jUr1BkQvANQGnuIhsmBoU77FE1PkXdmEXPnOmO188wIiiwjJc9afL683jc0:1wlAzS:5d0uwnXG--efSp88oXsURCxzZ3MairosZLU2sMGzrbI	2026-08-01 14:46:26.196866-05
\.


--
-- Data for Name: honeypot_ataquehoneypot; Type: TABLE DATA; Schema: public; Owner: cyberedu_user
--

COPY public.honeypot_ataquehoneypot (id, ip_origen, usuario_probado, contrasena_probada, protocolo, sesion_cowrie, eventid_original, timestamp_evento, fecha_ingesta, procesado, tipo_ataque_id) FROM stdin;
3	10.0.2.2	karo	2026*	ssh	8cdcea18d505	cowrie.login.failed	2026-07-10 06:59:55.16153-05	2026-07-18 10:45:48.533814-05	t	1
2	10.0.2.2	karo	karol123	ssh	8cdcea18d505	cowrie.login.failed	2026-07-10 06:59:50.563064-05	2026-07-18 10:45:48.527839-05	t	1
1	10.0.2.2	karo	5845	ssh	8cdcea18d505	cowrie.login.failed	2026-07-10 06:59:45.21689-05	2026-07-18 10:45:48.523277-05	t	1
\.


--
-- Data for Name: retos_puntuacion_insignia; Type: TABLE DATA; Schema: public; Owner: cyberedu_user
--

COPY public.retos_puntuacion_insignia (id, nombre, descripcion, condicion_logro, icono) FROM stdin;
1	Primer paso	Completa tu primer reto correctamente.	1 reto correct	
\.


--
-- Data for Name: retos_puntuacion_intentoreto; Type: TABLE DATA; Schema: public; Owner: cyberedu_user
--

COPY public.retos_puntuacion_intentoreto (id, es_correcto, xp_otorgado, fecha_intento, estudiante_id, respuesta_seleccionada_id, reto_id) FROM stdin;
1	t	20	2026-07-17 06:24:50.457833-05	3	1	1
2	t	20	2026-07-17 06:29:50.928069-05	3	1	1
3	t	20	2026-07-17 06:45:10.50294-05	3	1	1
\.


--
-- Data for Name: retos_puntuacion_nivel; Type: TABLE DATA; Schema: public; Owner: cyberedu_user
--

COPY public.retos_puntuacion_nivel (id, numero_nivel, nombre_nivel, xp_minimo, xp_maximo) FROM stdin;
1	1	Aprendiz	0	99
2	2	Explorador	100	299
3	3	Guardian	300	\N
\.


--
-- Data for Name: retos_puntuacion_opcionrespuesta; Type: TABLE DATA; Schema: public; Owner: cyberedu_user
--

COPY public.retos_puntuacion_opcionrespuesta (id, texto_opcion, es_correcta, pregunta_id) FROM stdin;
1	Fuerza bruta SSH	t	1
2	Ataque de phishing	f	1
3	Inyección SQL	f	1
4	Ataque DDoS	f	1
5	Fuerza bruta SSH	t	2
6	Ataque de phishing	f	2
7	Inyección SQL	f	2
8	Ataque DDoS	f	2
13	Fuerza bruta SSH	t	4
14	Ataque de phishing	f	4
15	Inyección SQL	f	4
16	Ataque DDoS	f	4
21	Fuerza bruta SSH	t	6
22	Ataque de phishing	f	6
23	Inyección SQL	f	6
24	Ataque DDoS	f	6
\.


--
-- Data for Name: retos_puntuacion_perfilestudiante; Type: TABLE DATA; Schema: public; Owner: cyberedu_user
--

COPY public.retos_puntuacion_perfilestudiante (id, xp_total, nivel_id, usuario_id) FROM stdin;
1	60	1	3
2	0	1	1
\.


--
-- Data for Name: retos_puntuacion_plantillaopcionrespuesta; Type: TABLE DATA; Schema: public; Owner: cyberedu_user
--

COPY public.retos_puntuacion_plantillaopcionrespuesta (id, texto_opcion, es_correcta, plantilla_id) FROM stdin;
1	Fuerza bruta SSH	t	1
2	Ataque de phishing	f	1
3	Inyección SQL	f	1
4	Ataque DDoS	f	1
\.


--
-- Data for Name: retos_puntuacion_plantillareto; Type: TABLE DATA; Schema: public; Owner: cyberedu_user
--

COPY public.retos_puntuacion_plantillareto (id, titulo, descripcion, xp_recompensa, tipo_ataque_id, enunciado_pregunta) FROM stdin;
1	Identifica el ataque SSH	Un atacante intentó múltiples combinaciones de usuario y contraseña contra el servidor SSH.	20	1	¿Qué tipo de ataque representa este evento?
\.


--
-- Data for Name: retos_puntuacion_preguntaquiz; Type: TABLE DATA; Schema: public; Owner: cyberedu_user
--

COPY public.retos_puntuacion_preguntaquiz (id, enunciado, orden, reto_id) FROM stdin;
1	¿Qué tipo de ataque representa este evento?	1	1
2	¿Qué tipo de ataque representa este evento?	1	2
4	¿Qué tipo de ataque representa este evento?	1	4
6	¿Qué tipo de ataque representa este evento?	1	6
\.


--
-- Data for Name: retos_puntuacion_reto; Type: TABLE DATA; Schema: public; Owner: cyberedu_user
--

COPY public.retos_puntuacion_reto (id, fecha_generacion, activo, curso_id, plantilla_id, ataque_origen_id) FROM stdin;
1	2026-07-17 06:16:57.62611-05	t	1	1	\N
2	2026-07-18 16:03:29.998732-05	t	1	1	3
4	2026-07-18 16:03:30.048766-05	t	1	1	2
6	2026-07-18 16:03:30.07489-05	t	1	1	1
\.


--
-- Data for Name: retos_puntuacion_tipoataque; Type: TABLE DATA; Schema: public; Owner: cyberedu_user
--

COPY public.retos_puntuacion_tipoataque (id, nombre, descripcion) FROM stdin;
1	Fuerza bruta SSH	Múltiples intentos de acceso probando distintas combinaciones de usuario y contraseña por SSH.
\.


--
-- Data for Name: retos_puntuacion_usuarioinsignia; Type: TABLE DATA; Schema: public; Owner: cyberedu_user
--

COPY public.retos_puntuacion_usuarioinsignia (id, fecha_obtencion, insignia_id, usuario_id) FROM stdin;
1	2026-07-17 06:29:50.936376-05	1	3
\.


--
-- Data for Name: usuarios_usuario; Type: TABLE DATA; Schema: public; Owner: cyberedu_user
--

COPY public.usuarios_usuario (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, rol, telegram_chat_id, telegram_vinculado, codigo_vinculacion_expira, codigo_vinculacion_telegram) FROM stdin;
2	pbkdf2_sha256$1200000$yZiQicRBGSGxRaI351gKGQ$SeKEBvs7fW3yBoYHFg6gBl64W1Y7T+nMzX9g06rucp4=	\N	f	estudiante_prueba			prueba@correo.com	f	t	2026-07-10 10:09:06.146231-05	estudiante	\N	f	\N	\N
4	pbkdf2_sha256$1200000$ocCguPGlwtYMYIqILnnZ59$G8M1w3LNKbxqnaSe+Ur/rhkYsf40g4D+3Z7aS3HD420=	\N	f	karol				f	t	2026-07-10 10:40:00.625659-05	estudiante	\N	f	\N	\N
5	pbkdf2_sha256$1200000$LRkj9DX68LpovirjSxkGao$jyktUODg2lO8jSh+DwJsmx8BKReqn98dptXIEzdmmBg=	\N	f	profesor_prueba			profesor@correo.com	f	t	2026-07-16 19:57:50.533106-05	profesor	\N	f	\N	\N
1	pbkdf2_sha256$1200000$wzfon4XWNAX15Tu7bU4fEt$5TXqbZvkcEaefOabxoaCy/uSbAKefV4haJIybo1pCyA=	2026-07-18 14:46:26.194893-05	t	admin				t	t	2026-07-09 22:30:12.887664-05	admin	\N	f	\N	\N
3	pbkdf2_sha256$1200000$hPnNWRCbP9SRhK1aNIF59k$DJyunMbU+IKddzW0R2Lcbh8JxoRHrmVy86YOUW81JRA=	\N	f	estudiante_prueba2			prueba2@correo.com	f	t	2026-07-10 10:29:52.846208-05	estudiante	8732012344	t	\N	\N
\.


--
-- Data for Name: usuarios_usuario_groups; Type: TABLE DATA; Schema: public; Owner: cyberedu_user
--

COPY public.usuarios_usuario_groups (id, usuario_id, group_id) FROM stdin;
\.


--
-- Data for Name: usuarios_usuario_user_permissions; Type: TABLE DATA; Schema: public; Owner: cyberedu_user
--

COPY public.usuarios_usuario_user_permissions (id, usuario_id, permission_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cyberedu_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cyberedu_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cyberedu_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 80, true);


--
-- Name: cursos_curso_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cyberedu_user
--

SELECT pg_catalog.setval('public.cursos_curso_id_seq', 2, true);


--
-- Name: cursos_inscripcion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cyberedu_user
--

SELECT pg_catalog.setval('public.cursos_inscripcion_id_seq', 2, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cyberedu_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 12, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cyberedu_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 20, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cyberedu_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 25, true);


--
-- Name: honeypot_ataquehoneypot_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cyberedu_user
--

SELECT pg_catalog.setval('public.honeypot_ataquehoneypot_id_seq', 3, true);


--
-- Name: retos_puntuacion_insignia_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cyberedu_user
--

SELECT pg_catalog.setval('public.retos_puntuacion_insignia_id_seq', 1, true);


--
-- Name: retos_puntuacion_intentoreto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cyberedu_user
--

SELECT pg_catalog.setval('public.retos_puntuacion_intentoreto_id_seq', 3, true);


--
-- Name: retos_puntuacion_nivel_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cyberedu_user
--

SELECT pg_catalog.setval('public.retos_puntuacion_nivel_id_seq', 3, true);


--
-- Name: retos_puntuacion_opcionrespuesta_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cyberedu_user
--

SELECT pg_catalog.setval('public.retos_puntuacion_opcionrespuesta_id_seq', 28, true);


--
-- Name: retos_puntuacion_perfilestudiante_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cyberedu_user
--

SELECT pg_catalog.setval('public.retos_puntuacion_perfilestudiante_id_seq', 2, true);


--
-- Name: retos_puntuacion_plantillaopcionrespuesta_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cyberedu_user
--

SELECT pg_catalog.setval('public.retos_puntuacion_plantillaopcionrespuesta_id_seq', 4, true);


--
-- Name: retos_puntuacion_plantillareto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cyberedu_user
--

SELECT pg_catalog.setval('public.retos_puntuacion_plantillareto_id_seq', 1, true);


--
-- Name: retos_puntuacion_preguntaquiz_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cyberedu_user
--

SELECT pg_catalog.setval('public.retos_puntuacion_preguntaquiz_id_seq', 7, true);


--
-- Name: retos_puntuacion_reto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cyberedu_user
--

SELECT pg_catalog.setval('public.retos_puntuacion_reto_id_seq', 7, true);


--
-- Name: retos_puntuacion_tipoataque_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cyberedu_user
--

SELECT pg_catalog.setval('public.retos_puntuacion_tipoataque_id_seq', 1, true);


--
-- Name: retos_puntuacion_usuarioinsignia_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cyberedu_user
--

SELECT pg_catalog.setval('public.retos_puntuacion_usuarioinsignia_id_seq', 1, true);


--
-- Name: usuarios_usuario_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cyberedu_user
--

SELECT pg_catalog.setval('public.usuarios_usuario_groups_id_seq', 1, false);


--
-- Name: usuarios_usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cyberedu_user
--

SELECT pg_catalog.setval('public.usuarios_usuario_id_seq', 5, true);


--
-- Name: usuarios_usuario_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cyberedu_user
--

SELECT pg_catalog.setval('public.usuarios_usuario_user_permissions_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: cursos_curso cursos_curso_pkey; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.cursos_curso
    ADD CONSTRAINT cursos_curso_pkey PRIMARY KEY (id);


--
-- Name: cursos_inscripcion cursos_inscripcion_estudiante_id_curso_id_76df6c87_uniq; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.cursos_inscripcion
    ADD CONSTRAINT cursos_inscripcion_estudiante_id_curso_id_76df6c87_uniq UNIQUE (estudiante_id, curso_id);


--
-- Name: cursos_inscripcion cursos_inscripcion_pkey; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.cursos_inscripcion
    ADD CONSTRAINT cursos_inscripcion_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: honeypot_ataquehoneypot honeypot_ataquehoneypot_pkey; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.honeypot_ataquehoneypot
    ADD CONSTRAINT honeypot_ataquehoneypot_pkey PRIMARY KEY (id);


--
-- Name: honeypot_ataquehoneypot honeypot_ataquehoneypot_sesion_cowrie_eventid_or_a3b184d1_uniq; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.honeypot_ataquehoneypot
    ADD CONSTRAINT honeypot_ataquehoneypot_sesion_cowrie_eventid_or_a3b184d1_uniq UNIQUE (sesion_cowrie, eventid_original, timestamp_evento);


--
-- Name: retos_puntuacion_insignia retos_puntuacion_insignia_nombre_key; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_insignia
    ADD CONSTRAINT retos_puntuacion_insignia_nombre_key UNIQUE (nombre);


--
-- Name: retos_puntuacion_insignia retos_puntuacion_insignia_pkey; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_insignia
    ADD CONSTRAINT retos_puntuacion_insignia_pkey PRIMARY KEY (id);


--
-- Name: retos_puntuacion_intentoreto retos_puntuacion_intentoreto_pkey; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_intentoreto
    ADD CONSTRAINT retos_puntuacion_intentoreto_pkey PRIMARY KEY (id);


--
-- Name: retos_puntuacion_nivel retos_puntuacion_nivel_numero_nivel_key; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_nivel
    ADD CONSTRAINT retos_puntuacion_nivel_numero_nivel_key UNIQUE (numero_nivel);


--
-- Name: retos_puntuacion_nivel retos_puntuacion_nivel_pkey; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_nivel
    ADD CONSTRAINT retos_puntuacion_nivel_pkey PRIMARY KEY (id);


--
-- Name: retos_puntuacion_opcionrespuesta retos_puntuacion_opcionrespuesta_pkey; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_opcionrespuesta
    ADD CONSTRAINT retos_puntuacion_opcionrespuesta_pkey PRIMARY KEY (id);


--
-- Name: retos_puntuacion_perfilestudiante retos_puntuacion_perfilestudiante_pkey; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_perfilestudiante
    ADD CONSTRAINT retos_puntuacion_perfilestudiante_pkey PRIMARY KEY (id);


--
-- Name: retos_puntuacion_perfilestudiante retos_puntuacion_perfilestudiante_usuario_id_key; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_perfilestudiante
    ADD CONSTRAINT retos_puntuacion_perfilestudiante_usuario_id_key UNIQUE (usuario_id);


--
-- Name: retos_puntuacion_plantillaopcionrespuesta retos_puntuacion_plantillaopcionrespuesta_pkey; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_plantillaopcionrespuesta
    ADD CONSTRAINT retos_puntuacion_plantillaopcionrespuesta_pkey PRIMARY KEY (id);


--
-- Name: retos_puntuacion_plantillareto retos_puntuacion_plantillareto_pkey; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_plantillareto
    ADD CONSTRAINT retos_puntuacion_plantillareto_pkey PRIMARY KEY (id);


--
-- Name: retos_puntuacion_preguntaquiz retos_puntuacion_preguntaquiz_pkey; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_preguntaquiz
    ADD CONSTRAINT retos_puntuacion_preguntaquiz_pkey PRIMARY KEY (id);


--
-- Name: retos_puntuacion_reto retos_puntuacion_reto_ataque_origen_id_curso_id_3d51f73b_uniq; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_reto
    ADD CONSTRAINT retos_puntuacion_reto_ataque_origen_id_curso_id_3d51f73b_uniq UNIQUE (ataque_origen_id, curso_id);


--
-- Name: retos_puntuacion_reto retos_puntuacion_reto_pkey; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_reto
    ADD CONSTRAINT retos_puntuacion_reto_pkey PRIMARY KEY (id);


--
-- Name: retos_puntuacion_tipoataque retos_puntuacion_tipoataque_nombre_key; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_tipoataque
    ADD CONSTRAINT retos_puntuacion_tipoataque_nombre_key UNIQUE (nombre);


--
-- Name: retos_puntuacion_tipoataque retos_puntuacion_tipoataque_pkey; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_tipoataque
    ADD CONSTRAINT retos_puntuacion_tipoataque_pkey PRIMARY KEY (id);


--
-- Name: retos_puntuacion_usuarioinsignia retos_puntuacion_usuario_usuario_id_insignia_id_d093c031_uniq; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_usuarioinsignia
    ADD CONSTRAINT retos_puntuacion_usuario_usuario_id_insignia_id_d093c031_uniq UNIQUE (usuario_id, insignia_id);


--
-- Name: retos_puntuacion_usuarioinsignia retos_puntuacion_usuarioinsignia_pkey; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_usuarioinsignia
    ADD CONSTRAINT retos_puntuacion_usuarioinsignia_pkey PRIMARY KEY (id);


--
-- Name: usuarios_usuario_groups usuarios_usuario_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.usuarios_usuario_groups
    ADD CONSTRAINT usuarios_usuario_groups_pkey PRIMARY KEY (id);


--
-- Name: usuarios_usuario_groups usuarios_usuario_groups_usuario_id_group_id_4ed5b09e_uniq; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.usuarios_usuario_groups
    ADD CONSTRAINT usuarios_usuario_groups_usuario_id_group_id_4ed5b09e_uniq UNIQUE (usuario_id, group_id);


--
-- Name: usuarios_usuario usuarios_usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.usuarios_usuario
    ADD CONSTRAINT usuarios_usuario_pkey PRIMARY KEY (id);


--
-- Name: usuarios_usuario_user_permissions usuarios_usuario_user_pe_usuario_id_permission_id_217cadcd_uniq; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.usuarios_usuario_user_permissions
    ADD CONSTRAINT usuarios_usuario_user_pe_usuario_id_permission_id_217cadcd_uniq UNIQUE (usuario_id, permission_id);


--
-- Name: usuarios_usuario_user_permissions usuarios_usuario_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.usuarios_usuario_user_permissions
    ADD CONSTRAINT usuarios_usuario_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: usuarios_usuario usuarios_usuario_username_key; Type: CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.usuarios_usuario
    ADD CONSTRAINT usuarios_usuario_username_key UNIQUE (username);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: cursos_curso_profesor_id_41fe36bc; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX cursos_curso_profesor_id_41fe36bc ON public.cursos_curso USING btree (profesor_id);


--
-- Name: cursos_inscripcion_curso_id_f32ce052; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX cursos_inscripcion_curso_id_f32ce052 ON public.cursos_inscripcion USING btree (curso_id);


--
-- Name: cursos_inscripcion_estudiante_id_ad2988ed; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX cursos_inscripcion_estudiante_id_ad2988ed ON public.cursos_inscripcion USING btree (estudiante_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: honeypot_ataquehoneypot_tipo_ataque_id_8288bdb6; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX honeypot_ataquehoneypot_tipo_ataque_id_8288bdb6 ON public.honeypot_ataquehoneypot USING btree (tipo_ataque_id);


--
-- Name: retos_puntuacion_insignia_nombre_3447be34_like; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX retos_puntuacion_insignia_nombre_3447be34_like ON public.retos_puntuacion_insignia USING btree (nombre varchar_pattern_ops);


--
-- Name: retos_puntuacion_intentoreto_estudiante_id_6df02633; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX retos_puntuacion_intentoreto_estudiante_id_6df02633 ON public.retos_puntuacion_intentoreto USING btree (estudiante_id);


--
-- Name: retos_puntuacion_intentoreto_respuesta_seleccionada_id_04455d80; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX retos_puntuacion_intentoreto_respuesta_seleccionada_id_04455d80 ON public.retos_puntuacion_intentoreto USING btree (respuesta_seleccionada_id);


--
-- Name: retos_puntuacion_intentoreto_reto_id_5d9fc9ce; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX retos_puntuacion_intentoreto_reto_id_5d9fc9ce ON public.retos_puntuacion_intentoreto USING btree (reto_id);


--
-- Name: retos_puntuacion_opcionrespuesta_pregunta_id_34dd187a; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX retos_puntuacion_opcionrespuesta_pregunta_id_34dd187a ON public.retos_puntuacion_opcionrespuesta USING btree (pregunta_id);


--
-- Name: retos_puntuacion_perfilestudiante_nivel_id_46f482d1; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX retos_puntuacion_perfilestudiante_nivel_id_46f482d1 ON public.retos_puntuacion_perfilestudiante USING btree (nivel_id);


--
-- Name: retos_puntuacion_plantillaopcionrespuesta_plantilla_id_ca0f7ada; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX retos_puntuacion_plantillaopcionrespuesta_plantilla_id_ca0f7ada ON public.retos_puntuacion_plantillaopcionrespuesta USING btree (plantilla_id);


--
-- Name: retos_puntuacion_plantillareto_tipo_ataque_id_77b0d9a0; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX retos_puntuacion_plantillareto_tipo_ataque_id_77b0d9a0 ON public.retos_puntuacion_plantillareto USING btree (tipo_ataque_id);


--
-- Name: retos_puntuacion_preguntaquiz_reto_id_94d187fd; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX retos_puntuacion_preguntaquiz_reto_id_94d187fd ON public.retos_puntuacion_preguntaquiz USING btree (reto_id);


--
-- Name: retos_puntuacion_reto_ataque_origen_id_75362caa; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX retos_puntuacion_reto_ataque_origen_id_75362caa ON public.retos_puntuacion_reto USING btree (ataque_origen_id);


--
-- Name: retos_puntuacion_reto_curso_id_d8b10467; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX retos_puntuacion_reto_curso_id_d8b10467 ON public.retos_puntuacion_reto USING btree (curso_id);


--
-- Name: retos_puntuacion_reto_plantilla_id_620c3ba9; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX retos_puntuacion_reto_plantilla_id_620c3ba9 ON public.retos_puntuacion_reto USING btree (plantilla_id);


--
-- Name: retos_puntuacion_tipoataque_nombre_fbd58d94_like; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX retos_puntuacion_tipoataque_nombre_fbd58d94_like ON public.retos_puntuacion_tipoataque USING btree (nombre varchar_pattern_ops);


--
-- Name: retos_puntuacion_usuarioinsignia_insignia_id_87bd9ad5; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX retos_puntuacion_usuarioinsignia_insignia_id_87bd9ad5 ON public.retos_puntuacion_usuarioinsignia USING btree (insignia_id);


--
-- Name: retos_puntuacion_usuarioinsignia_usuario_id_25a92b6e; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX retos_puntuacion_usuarioinsignia_usuario_id_25a92b6e ON public.retos_puntuacion_usuarioinsignia USING btree (usuario_id);


--
-- Name: usuarios_usuario_groups_group_id_e77f6dcf; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX usuarios_usuario_groups_group_id_e77f6dcf ON public.usuarios_usuario_groups USING btree (group_id);


--
-- Name: usuarios_usuario_groups_usuario_id_7a34077f; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX usuarios_usuario_groups_usuario_id_7a34077f ON public.usuarios_usuario_groups USING btree (usuario_id);


--
-- Name: usuarios_usuario_user_permissions_permission_id_4e5c0f2f; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX usuarios_usuario_user_permissions_permission_id_4e5c0f2f ON public.usuarios_usuario_user_permissions USING btree (permission_id);


--
-- Name: usuarios_usuario_user_permissions_usuario_id_60aeea80; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX usuarios_usuario_user_permissions_usuario_id_60aeea80 ON public.usuarios_usuario_user_permissions USING btree (usuario_id);


--
-- Name: usuarios_usuario_username_be9def2b_like; Type: INDEX; Schema: public; Owner: cyberedu_user
--

CREATE INDEX usuarios_usuario_username_be9def2b_like ON public.usuarios_usuario USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cursos_curso cursos_curso_profesor_id_41fe36bc_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.cursos_curso
    ADD CONSTRAINT cursos_curso_profesor_id_41fe36bc_fk_usuarios_usuario_id FOREIGN KEY (profesor_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cursos_inscripcion cursos_inscripcion_curso_id_f32ce052_fk_cursos_curso_id; Type: FK CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.cursos_inscripcion
    ADD CONSTRAINT cursos_inscripcion_curso_id_f32ce052_fk_cursos_curso_id FOREIGN KEY (curso_id) REFERENCES public.cursos_curso(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cursos_inscripcion cursos_inscripcion_estudiante_id_ad2988ed_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.cursos_inscripcion
    ADD CONSTRAINT cursos_inscripcion_estudiante_id_ad2988ed_fk_usuarios_ FOREIGN KEY (estudiante_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_usuarios_usuario_id FOREIGN KEY (user_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: honeypot_ataquehoneypot honeypot_ataquehoney_tipo_ataque_id_8288bdb6_fk_retos_pun; Type: FK CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.honeypot_ataquehoneypot
    ADD CONSTRAINT honeypot_ataquehoney_tipo_ataque_id_8288bdb6_fk_retos_pun FOREIGN KEY (tipo_ataque_id) REFERENCES public.retos_puntuacion_tipoataque(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: retos_puntuacion_intentoreto retos_puntuacion_int_estudiante_id_6df02633_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_intentoreto
    ADD CONSTRAINT retos_puntuacion_int_estudiante_id_6df02633_fk_usuarios_ FOREIGN KEY (estudiante_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: retos_puntuacion_intentoreto retos_puntuacion_int_respuesta_selecciona_04455d80_fk_retos_pun; Type: FK CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_intentoreto
    ADD CONSTRAINT retos_puntuacion_int_respuesta_selecciona_04455d80_fk_retos_pun FOREIGN KEY (respuesta_seleccionada_id) REFERENCES public.retos_puntuacion_opcionrespuesta(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: retos_puntuacion_intentoreto retos_puntuacion_int_reto_id_5d9fc9ce_fk_retos_pun; Type: FK CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_intentoreto
    ADD CONSTRAINT retos_puntuacion_int_reto_id_5d9fc9ce_fk_retos_pun FOREIGN KEY (reto_id) REFERENCES public.retos_puntuacion_reto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: retos_puntuacion_opcionrespuesta retos_puntuacion_opc_pregunta_id_34dd187a_fk_retos_pun; Type: FK CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_opcionrespuesta
    ADD CONSTRAINT retos_puntuacion_opc_pregunta_id_34dd187a_fk_retos_pun FOREIGN KEY (pregunta_id) REFERENCES public.retos_puntuacion_preguntaquiz(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: retos_puntuacion_perfilestudiante retos_puntuacion_per_nivel_id_46f482d1_fk_retos_pun; Type: FK CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_perfilestudiante
    ADD CONSTRAINT retos_puntuacion_per_nivel_id_46f482d1_fk_retos_pun FOREIGN KEY (nivel_id) REFERENCES public.retos_puntuacion_nivel(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: retos_puntuacion_perfilestudiante retos_puntuacion_per_usuario_id_0614f58c_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_perfilestudiante
    ADD CONSTRAINT retos_puntuacion_per_usuario_id_0614f58c_fk_usuarios_ FOREIGN KEY (usuario_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: retos_puntuacion_plantillaopcionrespuesta retos_puntuacion_pla_plantilla_id_ca0f7ada_fk_retos_pun; Type: FK CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_plantillaopcionrespuesta
    ADD CONSTRAINT retos_puntuacion_pla_plantilla_id_ca0f7ada_fk_retos_pun FOREIGN KEY (plantilla_id) REFERENCES public.retos_puntuacion_plantillareto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: retos_puntuacion_plantillareto retos_puntuacion_pla_tipo_ataque_id_77b0d9a0_fk_retos_pun; Type: FK CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_plantillareto
    ADD CONSTRAINT retos_puntuacion_pla_tipo_ataque_id_77b0d9a0_fk_retos_pun FOREIGN KEY (tipo_ataque_id) REFERENCES public.retos_puntuacion_tipoataque(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: retos_puntuacion_preguntaquiz retos_puntuacion_pre_reto_id_94d187fd_fk_retos_pun; Type: FK CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_preguntaquiz
    ADD CONSTRAINT retos_puntuacion_pre_reto_id_94d187fd_fk_retos_pun FOREIGN KEY (reto_id) REFERENCES public.retos_puntuacion_reto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: retos_puntuacion_reto retos_puntuacion_ret_ataque_origen_id_75362caa_fk_honeypot_; Type: FK CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_reto
    ADD CONSTRAINT retos_puntuacion_ret_ataque_origen_id_75362caa_fk_honeypot_ FOREIGN KEY (ataque_origen_id) REFERENCES public.honeypot_ataquehoneypot(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: retos_puntuacion_reto retos_puntuacion_ret_plantilla_id_620c3ba9_fk_retos_pun; Type: FK CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_reto
    ADD CONSTRAINT retos_puntuacion_ret_plantilla_id_620c3ba9_fk_retos_pun FOREIGN KEY (plantilla_id) REFERENCES public.retos_puntuacion_plantillareto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: retos_puntuacion_reto retos_puntuacion_reto_curso_id_d8b10467_fk_cursos_curso_id; Type: FK CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_reto
    ADD CONSTRAINT retos_puntuacion_reto_curso_id_d8b10467_fk_cursos_curso_id FOREIGN KEY (curso_id) REFERENCES public.cursos_curso(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: retos_puntuacion_usuarioinsignia retos_puntuacion_usu_insignia_id_87bd9ad5_fk_retos_pun; Type: FK CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_usuarioinsignia
    ADD CONSTRAINT retos_puntuacion_usu_insignia_id_87bd9ad5_fk_retos_pun FOREIGN KEY (insignia_id) REFERENCES public.retos_puntuacion_insignia(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: retos_puntuacion_usuarioinsignia retos_puntuacion_usu_usuario_id_25a92b6e_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.retos_puntuacion_usuarioinsignia
    ADD CONSTRAINT retos_puntuacion_usu_usuario_id_25a92b6e_fk_usuarios_ FOREIGN KEY (usuario_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuario_groups usuarios_usuario_gro_usuario_id_7a34077f_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.usuarios_usuario_groups
    ADD CONSTRAINT usuarios_usuario_gro_usuario_id_7a34077f_fk_usuarios_ FOREIGN KEY (usuario_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuario_groups usuarios_usuario_groups_group_id_e77f6dcf_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.usuarios_usuario_groups
    ADD CONSTRAINT usuarios_usuario_groups_group_id_e77f6dcf_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuario_user_permissions usuarios_usuario_use_permission_id_4e5c0f2f_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.usuarios_usuario_user_permissions
    ADD CONSTRAINT usuarios_usuario_use_permission_id_4e5c0f2f_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuario_user_permissions usuarios_usuario_use_usuario_id_60aeea80_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: cyberedu_user
--

ALTER TABLE ONLY public.usuarios_usuario_user_permissions
    ADD CONSTRAINT usuarios_usuario_use_usuario_id_60aeea80_fk_usuarios_ FOREIGN KEY (usuario_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO cyberedu_user;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO cyberedu_user;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO cyberedu_user;


--
-- PostgreSQL database dump complete
--

\unrestrict VHfBqszWjkkvfnvREOWVwWFxovAQs72tDbXJii2xqKUQHCeMaZX24Gstxhk0wif

