# Generated by Django 6.0.7 on 2026-07-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_vinculacion_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo_vinculacion_telegram',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
