# Generated by Django 6.0.7 on 2026-07-18 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retos_puntuacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtaqueHoneypot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_origen', models.GenericIPAddressField()),
                ('usuario_probado', models.CharField(blank=True, max_length=100)),
                ('contrasena_probada', models.CharField(blank=True, max_length=100)),
                ('protocolo', models.CharField(blank=True, max_length=20)),
                ('sesion_cowrie', models.CharField(max_length=64)),
                ('eventid_original', models.CharField(max_length=100)),
                ('timestamp_evento', models.DateTimeField()),
                ('fecha_ingesta', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
                ('tipo_ataque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ataques', to='retos_puntuacion.tipoataque')),
            ],
            options={
                'ordering': ['-timestamp_evento'],
                'unique_together': {('sesion_cowrie', 'eventid_original', 'timestamp_evento')},
            },
        ),
    ]
