# Generated by Django 4.2.30 on 2026-09-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0002_alter_ataquehoneypot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ataquehoneypot',
            name='detalle',
            field=models.CharField(blank=True, help_text='Comando ejecutado o archivo/URL descargado, según el tipo de evento.', max_length=255),
        ),
    ]
